### ISSUE TITLE
Handle recursive types?

### ISSUE THREAD

**Issue by pillowsoft** [typed-immutable/typed-immutable#12] opened 2015-10-17 16:31 UTC
Is there any way to handle recursive types? I.e.

```
var Node = Record({

**Comment by Gozala** [comment] 2016-06-23 21:50
Unfortunately I am no longer able to maintain this project, I apologize. If someone wishes to step up and take leadership of this project please respond to #21

**Comment by lukesneeringer** [comment] 2016-07-27 23:40
Duplicate of #13.

**Closed by lukesneeringer** 2016-07-27 23:40 UTC
